<div class="py-4 py-md-5"><div class="bg-white rounded-lg shadow-md p-3 p-md-4 space-y-4">
    <h2 class="text-xl font-bold mb-0">احکام کارگزینی</h2>
    @include('livewire.partials.flash')
    <form wire:submit.prevent="save" class="erp-ui-filter-bar"><div class="row g-2 g-md-3 align-items-end">
        <label class="erp-filter-field col-12 col-md-3">شماره حکم<input wire:model="form.number" dir="ltr"></label>
        <label class="erp-filter-field col-12 col-md-3">پرسنل<select wire:model="form.employee_id"><option value="">انتخاب کنید</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->full_name }} - {{ $employee->personnel_code ?: $employee->id }}</option>@endforeach</select></label>
        <label class="erp-filter-field col-12 col-md-2">نوع حکم<select wire:model="form.order_type"><option value="hire">استخدام</option><option value="position_change">تغییر سمت</option><option value="salary_change">تغییر حقوق</option><option value="contract_renewal">تمدید قرارداد</option><option value="termination">پایان همکاری</option></select></label>
        <label class="erp-filter-field col-12 col-md-2">نوع استخدام<select wire:model="form.employment_type"><option value="hourly">ساعتی</option><option value="monthly_contract">قرارداد ماهانه</option><option value="project_based">پروژه‌ای</option><option value="fixed_term">مدت معین</option><option value="permanent">دائم</option></select></label>
        <label class="erp-filter-field col-12 col-md-2">وضعیت بیمه<select wire:model="form.insurance_status"><option value="insured">مشمول بیمه</option><option value="not_insured">بدون بیمه</option><option value="exempt">معاف</option></select></label>
        <label class="erp-filter-field col-12 col-md-3">پست<select wire:model="form.position_id"><option value="">-</option>@foreach($positions as $position)<option value="{{ $position->id }}">{{ $position->title }}</option>@endforeach</select></label>
        <label class="erp-filter-field col-12 col-md-3">شغل<select wire:model="form.job_id"><option value="">-</option>@foreach($jobs as $job)<option value="{{ $job->id }}">{{ $job->title }}</option>@endforeach</select></label>
        <label class="erp-filter-field col-12 col-md-3">واحد<select wire:model="form.organization_unit_id"><option value="">-</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->title }}</option>@endforeach</select></label>
        <label class="erp-filter-field col-12 col-md-3">پروژه پیش‌فرض<select wire:model="form.default_project_id"><option value="">-</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></label>
        <label class="erp-filter-field col-12 col-md-2">تاریخ اثر<input wire:model="form.effective_date" dir="ltr"></label>
        <label class="erp-filter-field col-12 col-md-2">تاریخ پایان<input wire:model="form.end_date" dir="ltr"></label>
        <label class="erp-filter-field col-12 col-md-2">حقوق پایه<input type="number" wire:model="form.base_salary" dir="ltr"></label>
        <label class="erp-filter-field col-12 col-md-2">نرخ ساعتی<input type="number" wire:model="form.hourly_rate" dir="ltr"></label>
        <label class="erp-filter-field col-12 col-md-2">حق مسکن<input type="number" wire:model="form.housing_allowance" dir="ltr"></label>
        <label class="erp-filter-field col-12 col-md-2">بن/غذا<input type="number" wire:model="form.food_allowance" dir="ltr"></label>
        <label class="erp-filter-field col-12 col-md-2">حق اولاد<input type="number" wire:model="form.child_allowance" dir="ltr"></label>
        <label class="erp-filter-field col-12 col-md-2">ایاب و ذهاب<input type="number" wire:model="form.transportation_allowance" dir="ltr"></label>
        <label class="erp-filter-field col-12 col-md-4">مرکز هزینه<input wire:model="form.cost_center_code"></label>
        <label class="erp-filter-field col-12 col-md-6">یادداشت<input wire:model="form.notes"></label>
        <div class="col-12 col-md-2 d-grid d-sm-flex gap-2"><button class="erp-action-btn erp-action-edit">ذخیره</button><button type="button" wire:click="cancel" class="erp-action-btn">جدید</button></div>
    </div></form>
    <div class="erp-ui-filter-bar"><div class="row g-2"><label class="erp-filter-field col-12 col-md-6">جستجو<input wire:model.live.debounce.400ms="search"></label><label class="erp-filter-field col-12 col-md-3">وضعیت<select wire:model.live="status"><option value="">همه</option><option value="draft">پیش‌نویس</option><option value="approved">تایید شده</option></select></label><div class="col-12 col-md-3 d-grid"><button type="button" wire:click="clearFilters" class="erp-action-btn">حذف فیلتر</button></div></div></div>
    <div class="table-responsive"><table class="erp-ui-data-table w-full"><thead><tr><th>شماره</th><th>پرسنل</th><th>نوع</th><th>تاریخ اثر</th><th>پست</th><th>حقوق پایه</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>@forelse($orders as $order)<tr wire:key="order-{{ $order->id }}"><td>{{ $order->number }}</td><td>{{ $order->employee->full_name }}</td><td>{{ $order->order_type }}</td><td>{{ formatJalaliDateSafe($order->effective_date) }}</td><td>{{ $order->position?->title ?: '-' }}</td><td>{{ number_format((float) $order->base_salary) }}</td><td>{{ $order->status === 'approved' ? 'تایید شده' : 'پیش‌نویس' }}</td><td><div class="d-grid d-sm-flex gap-2">@if($order->status === 'approved')<button wire:click="revert({{ $order->id }})" wire:confirm="حکم از ثبت قطعی برگردد و قابل ویرایش شود؟" class="erp-action-btn erp-action-edit">برگشت از ثبت قطعی</button><span class="text-emerald-700 font-bold">ثبت قطعی</span>@else<button wire:click="edit({{ $order->id }})" class="erp-action-btn erp-action-edit">ویرایش</button><button wire:click="approve({{ $order->id }})" wire:confirm="حکم تایید شود؟" class="erp-action-btn erp-action-detail">تایید</button><button wire:click="delete({{ $order->id }})" wire:confirm="حذف شود؟" class="erp-action-btn erp-action-delete">حذف</button>@endif</div></td></tr>@empty<tr><td colspan="8" class="text-center py-6 text-slate-500">حکمی ثبت نشده است.</td></tr>@endforelse</tbody></table></div>
    {{ $orders->links() }}
</div></div>
